### ISSUE TITLE
Part of layout falls apart when the external fonts are not / can not be loaded

### ISSUE THREAD

**Issue by flarik** [rocketconf/rocketconf.eu#6]
At the moment the external webfonts are not / can not be loaded, the font-size/line-height causes trouble
## Chrome

![chrome](https://cloud.githubusercontent.com/assets/194395/7711826/88712dae-fe6d-11e4-8f0e-44d07d988f12.png)
## FireFox

![firefox](https://cloud.githubusercontent.com/assets/194395/7711831/921a62b2-fe6d-11e4-8de4-b9cae66b7105.png)

**Comment by RoelN** [comment]
This was because I was messing with the Typekit kit. Is fixed in the new site. Thanks for reporting!
